version: "3.3"

services:
  snikket_proxy:
    container_name: snikket-proxy
    image: snikket/snikket-web-proxy:beta
    env_file: snikket.conf
    network_mode: host
    volumes:
      - /etc/snikket/data:/snikket
      - acme:/var/www/html/.well-known/acme-challenge
    restart: "unless-stopped"
  snikket_certs:
    container_name: snikket-certs
    image: snikket/snikket-cert-manager:beta
    env_file: snikket.conf
    volumes:
      - /etc/snikket/data:/snikket
      - acme:/var/www/.well-known/acme-challenge
    restart: "unless-stopped"
  snikket_portal:
    container_name: snikket-portal
    image: snikket/snikket-web-portal:beta
    network_mode: host
    env_file: snikket.conf
    restart: "unless-stopped"
  snikket_server:
    container_name: snikket
    image: snikket/snikket-server:beta
    network_mode: host
    volumes:
      - /etc/snikket/data:/snikket
    env_file: snikket.conf
    restart: "unless-stopped"
  slidge-telegram:
    container_name: slidge-telegram
    image: docker.io/nicocool84/slidge-telegram:latest
    network_mode: host
    command:
      - --secret=putyoursecret here
      - --jid=the jid you set in your prosody.cfg.lua
      - --server=chat.yourserver.tld
    volumes:
      - /etc/snikket/slidge/telegram:/var/lib/slidge
  slidge-facebook:
    container_name: slidge-facebook
    image: docker.io/nicocool84/slidge-facebook:latest
    network_mode: host
    command:
      - --secret=putyoursecrethere
      - --jid=the jid you set in your prosody.cfg.lua
      - --server=chat.yourserver.tld
    volumes:
      - /etc/snikket/slidge/facebook:/var/lib/slidge

volumes:
  acme:




